import { Metadata } from "next";
import Image from "next/image";

export const metadata:Metadata = {
  title: 'Next.js 123',
  description: 'Generated by Next.js',
}

export default function Home() {
  return (
    <>
      <p>Home Page</p>
    </>

  );
}
